---
# tasks file for MichaelConrad.retropie

- include: do_configure_system.yml
  tags:
    - retropie
    - retropie_configure_system

- include: do_configure_retropie.yml
  tags:
    - retropie
    - retropie_configure_retropie
